model:
  activation: lrelu
  n_segments: 1
  n_classes: 1
  dataset: synth
  log_latents: false
  log_reconstruction: false
  prior: uniform
  latent_dim: 2
  n_layers: 3
  lr: 0.001
  prior_alpha: 1.0
  prior_beta: 1.0
  prior_mean: 0.0
  prior_var: 1.0
  decoder_var: 1.0e-04
  fix_prior: true
  beta: 1.0
  diag_posterior: true
data:
  batch_size: 64
  orthog: false
  mobius: true
  linear: false
  n_segments: 1
  mixing_layers: 1
  n_obs: 60000
  seed: 1
  n_classes: 1
  train_ratio: 0.7
  val_ratio: 0.2
  dataset: synth
  train_transforms: null
  val_transforms: null
  test_transforms: null
  dims: null
  synth_source: uniform
ckpt_path: null
