trainer:
  auto_select_gpus: false
  overfit_batches: 0.0
  max_epochs: 30
  gpus: 0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  log_every_n_steps: 50
