seed_everything: 1
trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      log_model: true
      project: experiment
      save_dir: ima_vae
  enable_checkpointing: true
  callbacks: null
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: 1
  auto_select_gpus: false
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 5
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 250
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  gpus: 1
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: null
  log_every_n_steps: 250
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: false
  deterministic: true
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: false
  replace_sampler_ddp: true
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  detect_anomaly: true
model:
  activation: lrelu
  n_segments: 1
  n_classes: 1
  dataset: synth
  log_latents: false
  log_reconstruction: false
  prior: uniform
  latent_dim: 2
  n_layers: 3
  lr: 0.001
  prior_alpha: 1.0
  prior_beta: 1.0
  prior_mean: 0.0
  prior_var: 1.0
  decoder_var: 1.0e-04
  fix_prior: true
  beta: 1.0
  diag_posterior: true
data:
  batch_size: 256
  orthog: false
  mobius: true
  ar_flow: false
  linear: false
  n_segments: 1
  mixing_layers: 1
  n_obs: 60000
  seed: 1
  n_classes: 1
  train_ratio: 0.7
  val_ratio: 0.2
  dataset: synth
  projective: false
  affine: false
  deltah: 0
  deltas: 0
  deltav: 0
  angle: false
  shape: false
  train_transforms: null
  val_transforms: null
  test_transforms: null
  dims: null
  synth_source: uniform